### ISSUE TITLE
Bird not returning to visible start position when game state buttons (replay and play) are hit

### ISSUE THREAD

**Issue by oshiogifted** [oshiogifted/MJ-Games#3]
It seems that when the replay button is clicked, the bird doesn't go back to its original start position. I believe the position of the bird should be changed, yes? @JohnParzival76

**Comment by JohnParzival76** [comment]
Yes it should be changed, I also saw the issue when I played it. The bird moves into a different location, it goes to (x=0, y=0) when replayed. https://gyazo.com/257a7925155a1911299f4f0e3e8d3dd2

**Comment by JohnParzival76** [comment]
And the bird is visible in scene view but not in game view LOOL

**Comment by oshiogifted** [comment]
> And the bird is visible in scene view but not in game view LOOL

yeah, this! So weird...

**Comment by JohnParzival76** [comment]
I solved this by changing the start position values because the bird was rendering behind the camera thus it disappearing when reset.
